"""GLAS: Granular Lab Acquisition System.

A production-quality acquisition and analysis platform built around a
Basler ace acA640-750um camera, for granular-material physics experiments.
"""

from glas.accelerometer import (
    AccelerometerRecording,
    VibrationMetrics,
    analyze_vibration,
    compute_gamma,
    compute_vibration_amplitude,
    compute_vibration_frequency,
    import_accelerometer_csv,
    plot_vibration_signal,
    synchronize_with_frames,
)
from glas.acquisition import Acquisition, AcquisitionStats
from glas.analysis import (
    BrazilNutTrajectory,
    ConvectionSummary,
    Detection,
    PackingField,
    PackingMetrics,
    PackingSummary,
    ParticleTracker,
    SegregationMetrics,
    SegregationSummary,
    TrackedParticle,
    VelocityField,
    analyze_brazil_nut,
    analyze_convection,
    analyze_packing,
    analyze_segregation,
    compute_brazil_nut_trajectory,
    compute_optical_flow,
    compute_packing_field,
    compute_packing_metrics,
    compute_segregation_metrics,
    compute_vorticity,
    detect_particles,
    identify_brazil_nut,
    link_nearest,
    plot_brazil_nut_trajectory,
    plot_packing_heatmap,
    plot_packing_summary,
    plot_segregation_summary,
    plot_velocity_heatmap,
    total_circulation,
    track_dataset,
)
from glas.camera import Camera
from glas.camera_info import CameraInfo, UsbDiagnostics, detect_cameras
from glas.camera_validator import (
    ROI,
    NumericRange,
    ROIBounds,
    validate_exposure_time,
    validate_gain,
    validate_pixel_format,
    validate_roi,
)
from glas.controller import RecorderController
from glas.dataset import (
    Dataset,
    DatasetValidationResult,
    create_experiment_folder,
    iter_frames,
    resolve_dataset_format,
    validate_dataset,
)
from glas.display import PreviewWindow, render_frame, render_histogram
from glas.exceptions import (
    AccelerometerError,
    AcquisitionError,
    BrazilNutError,
    CameraConfigurationError,
    CameraConnectionError,
    CameraDriverError,
    CameraError,
    CameraFeatureUnavailableError,
    CameraNotFoundError,
    ConfigurationError,
    ConvectionError,
    DatasetError,
    DatasetFormatError,
    DatasetIOError,
    DisplayError,
    ExperimentNotFoundError,
    ExportError,
    GLASError,
    HardwareError,
    InstrumentCommandError,
    InstrumentConnectionError,
    JSONValidationError,
    LoggingError,
    PackingError,
    RecorderError,
    SegregationError,
    SettingsError,
    WriterError,
)
from glas.experiment import (
    NAME_KEY,
    TAGS_KEY,
    ExperimentManager,
    ExperimentSummary,
    build_experiment_extra,
)
from glas.export import ExportFormat, ExportResult, export_dataset
from glas.frame import Frame, pixel_format_dtype
from glas.hardware import (
    DEFAULT_SCPI_PORT,
    AnalogInputDAQ,
    LabJackDAQ,
    NiDAQ,
    SCPIInstrument,
    SCPIOscilloscope,
    SCPITransport,
    ShakerCalibration,
    ShakerController,
    SiglentSDG1032X,
    SocketSCPITransport,
)
from glas.logger import configure_logging, get_logger
from glas.metadata import DatasetMetadata, load_metadata_json, save_metadata_json
from glas.monitor import PerformanceMonitor, PerformanceSnapshot
from glas.preview import Preview, ZoomRegion, apply_zoom
from glas.recorder import Recorder, RecorderProgress, RecorderState
from glas.ringbuffer import RingBuffer, RingBufferStats
from glas.settings import Settings
from glas.timestamps import TimestampLog, WallClockReference
from glas.version import VERSION_INFO, __version__
from glas.writer import DatasetWriter, WriterStats

__all__ = [
    "__version__",
    "VERSION_INFO",
    "GLASError",
    "ConfigurationError",
    "JSONValidationError",
    "LoggingError",
    "SettingsError",
    "CameraError",
    "CameraDriverError",
    "CameraNotFoundError",
    "CameraConnectionError",
    "CameraConfigurationError",
    "CameraFeatureUnavailableError",
    "AcquisitionError",
    "DatasetError",
    "DatasetFormatError",
    "DatasetIOError",
    "WriterError",
    "RecorderError",
    "DisplayError",
    "ExportError",
    "ExperimentNotFoundError",
    "BrazilNutError",
    "ConvectionError",
    "PackingError",
    "SegregationError",
    "AccelerometerError",
    "HardwareError",
    "InstrumentConnectionError",
    "InstrumentCommandError",
    "configure_logging",
    "get_logger",
    "Settings",
    "Camera",
    "CameraInfo",
    "UsbDiagnostics",
    "detect_cameras",
    "ROI",
    "NumericRange",
    "ROIBounds",
    "validate_exposure_time",
    "validate_gain",
    "validate_pixel_format",
    "validate_roi",
    "Frame",
    "pixel_format_dtype",
    "RingBuffer",
    "RingBufferStats",
    "Acquisition",
    "AcquisitionStats",
    "DatasetMetadata",
    "load_metadata_json",
    "save_metadata_json",
    "TimestampLog",
    "WallClockReference",
    "Dataset",
    "DatasetValidationResult",
    "create_experiment_folder",
    "iter_frames",
    "resolve_dataset_format",
    "validate_dataset",
    "DatasetWriter",
    "WriterStats",
    "Recorder",
    "RecorderState",
    "RecorderProgress",
    "RecorderController",
    "Preview",
    "ZoomRegion",
    "apply_zoom",
    "PreviewWindow",
    "render_frame",
    "render_histogram",
    "PerformanceMonitor",
    "PerformanceSnapshot",
    "ExportFormat",
    "ExportResult",
    "export_dataset",
    "ExperimentManager",
    "ExperimentSummary",
    "build_experiment_extra",
    "NAME_KEY",
    "TAGS_KEY",
    "Detection",
    "detect_particles",
    "link_nearest",
    "ParticleTracker",
    "TrackedParticle",
    "track_dataset",
    "BrazilNutTrajectory",
    "identify_brazil_nut",
    "compute_brazil_nut_trajectory",
    "plot_brazil_nut_trajectory",
    "analyze_brazil_nut",
    "VelocityField",
    "ConvectionSummary",
    "compute_optical_flow",
    "compute_vorticity",
    "total_circulation",
    "plot_velocity_heatmap",
    "analyze_convection",
    "PackingMetrics",
    "PackingSummary",
    "PackingField",
    "compute_packing_metrics",
    "compute_packing_field",
    "plot_packing_heatmap",
    "plot_packing_summary",
    "analyze_packing",
    "SegregationMetrics",
    "SegregationSummary",
    "compute_segregation_metrics",
    "plot_segregation_summary",
    "analyze_segregation",
    "AccelerometerRecording",
    "VibrationMetrics",
    "import_accelerometer_csv",
    "compute_vibration_frequency",
    "compute_gamma",
    "compute_vibration_amplitude",
    "plot_vibration_signal",
    "analyze_vibration",
    "synchronize_with_frames",
    "DEFAULT_SCPI_PORT",
    "SCPITransport",
    "SocketSCPITransport",
    "SCPIInstrument",
    "SiglentSDG1032X",
    "SCPIOscilloscope",
    "ShakerCalibration",
    "ShakerController",
    "AnalogInputDAQ",
    "LabJackDAQ",
    "NiDAQ",
]
